### ISSUE TITLE
Cannot extend from \yii\codeception\TestCase

### ISSUE THREAD

**Issue by jepster** [yiisoft/yii2-codeception#10]
If I try to extend from \yii\codeception\TestCase I'm always getting 

> Class 'yii\codeception\TestCase' not found 

Codeception itself runs properly. Tried to extend from root namespace and without (like in the documentation here on GitHub). My tests are located in a Yii2 module. yii2-codeception is installed via composer. I want to have the Yii2 application object in my unit test. Do you have any idea, what I can check?

**Comment by jepster** [comment]
I'm trying to run the tests by

> codecept run

**Comment by jepster** [comment]
Fixed - problem was that codeception wasn't installed into vendor directory by composer. It was installed globally. Codeception and yii2-codeception must be installed into the yii2 application (not global).

**Comment by samdark** [comment]
@jepster oh? It worked fine for me with global install...

**Comment by jepster** [comment]
@samdark I'm having still the problem. When I run my test class I get

> Class 'Yii' not found 
> in ... /vendor/yiisoft/yii2-codeception/TestCase.php:110

I don't know why. in vendor/bin/codecept symlink is

> require_once dirname(__FILE__).'/autoload.php';

so Yii "should" be loaded via composer autoloading. Have you any idea?

**Comment by samdark** [comment]
Nope.
