### ISSUE TITLE
Db connection doesn't close after test

### ISSUE THREAD

**Issue by kaiserfedor** [yiisoft/yii2-codeception#13]
Hi,
I have 84 tests (extended from `TestCase` class) and if I run it all together I get error: `FATAL: sorry, too many clients already`.
The problem is method `destroyApplication()` doesn't close db connection before destroy application. 
https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php#L134
Is that expected behaviour?

Problem can be resolved by `Yii::$app->db->close();` before `Yii::$app = null;`.
I use codeception 2.1.x-dev, Yii 2.0.6 and yii2-codeception dev-master (22e981b8).

This problem seems very similar to https://github.com/yiisoft/yii2/issues/9852

**Comment by cebe** [comment]
we do this already in the framework test cases and also for session here: https://github.com/yiisoft/yii2/blob/master/tests/TestCase.php#L84-L86 

could you add it and send a pull request?

**Comment by kaiserfedor** [comment]
I've created pull request https://github.com/yiisoft/yii2-codeception/pull/14
It fix session and db connection closing.

**Comment by klimov-paul** [comment]
Should not DB connection being closed by PDO on `__destruct()` automatically?

**Comment by kaiserfedor** [comment]
I guess it should, but it doesn't work if I don't call ```Yii::$app->db->close()``` explicitly

**Comment by samdark** [comment]
@klimov-paul no since PDO seems to be alive during the same request and is destroyed along with the overall context.

**Comment by klimov-paul** [comment]
We need to check if `Connection::__destructed()` invoked at `destroyApplication()`. It should: created application and its internal components should be destoyed and free the allocated memory.
If this does not happen, we need to check why.

**Comment by kaiserfedor** [comment]
@klimov-paul ```destroyApplication()``` is very simple now:
https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php#L132-L136
```Connection::__destructed()``` isn't invoked here and, by the way, I can't find ```__destructed()``` or  ```__destruct()``` in ```yii\db\Connection``` or parent classes.

**Comment by cebe** [comment]
It may not get destroyed due to circular references.

**Comment by kaiserfedor** [comment]
@klimov-paul @samdark 
```destroyApplication()``` doesn't destroy application instance, because there is reference to this instance in Yii2 codeception module (maybe somewhere else). That's why we have to close db connection explicitly.
