### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by slinstj** [yiisoft/yii2-codeception#23]
### What steps will reproduce the problem?
1. Access: http://www.yiiframework.com/doc-2.0/ext-codeception-index.html
2. Click in the links: "LICENSE" or "Documentation is at docs/guide/README.md.";

### What do you get instead?
*Unable to resolve the request "doc-2.0/LICENSE.md".*
*Unable to resolve the request "doc-2.0/docs/guide/README.md".*

**Comment by slinstj** [comment]
It is related to #9.

I can fix this but I cant find where since README in `yii2/extensions/codeception/docs/guide` is ok and not is the same used in the link cited above. But in yii2/docs/guide there is no ext-codeception-index.html to edit. 

Just need you point me the correct file to be fixed.

**Comment by samdark** [comment]
The problem is within the generator https://github.com/yiisoft/yii2-apidoc

**Comment by slinstj** [comment]
Do you mean a bug? Or would be enough to fix the docs and regenerate the guide via apidoc?

**Comment by samdark** [comment]
I'm not sure about it.

**Comment by cebe** [comment]
the links work fine on github but not on the rendered output of the apidoc. it could be added to it somehow but we need to develop some conventions for that.

**Comment by slinstj** [comment]
I've never used yii2-apidoc and I really dont know how it works internally but in a very superficial investigation it seems to be possible to determine what extension is being parsed (by the folder extensions). So, maybe a mapper array in which keys are extension ids and values are baseUrl or a convention based in ext names would be useful to determine a final link. 

```php
// with mapper
$mapper = [
    'codeception' => 'https://github.com/yiisoft/yii2-codeception/blob/master',
   // ...
];

$baseUrl = array_key_exists($extensionId, $mapper) ? $mapper[$extensionId] : '';
$finalLink = $baseUrl . DIRECTORY_SEPARATOR . $originalLink;

// with convention since yii2 has already some conventions for ext names

$finalLink =  'https://github.com/yiisoft/yii2-' . $extensionId . '/blob/master/', . $originalLink;
```

**Comment by slinstj** [comment]
I am closing this because is really a duplicate of #9 and the "problem" is not exactly in yii2-codeception docs but in yii2-apidoc generation. Feel free to reopen if needed.
