### ISSUE TITLE
Missing dependence for Codeception

### ISSUE THREAD

**Issue by Lexxtor** [yiisoft/yii2-codeception#27]
I'm instaled this package via composer.
It have a `TestCase` class that extends `Test`. But `Test` class is missing.

https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php#L12
Here I see:  `use Codeception\TestCase\Test;`
But where is `Codeception\TestCase\Test;`, in what package? How to install it?

**Comment by cebe** [comment]
duplicate of #3, codeception is not in the dependencies because it is expected to be used as .phar file which already contains these files. Should be documented though.
