### ISSUE TITLE
DbTestCase not working in Codeception 2.2.4

### ISSUE THREAD

**Issue by StalkAlex** [yiisoft/yii2-codeception#30]
Here's main issue 
https://github.com/Codeception/Codeception/issues/3442

I thought maybe someone here could explain how to deal with tests that inherit DbTestCase, it's not working anymore, how to fix this problem besides rolling back and using codeception way of loading fixtures? I want something like this to work again.
```php
public function globalFixtures()
  {
    return [
      'class' => InitDbFixture::className(),
      'initScript' => '/path/to/initdb.php'
    ];
  }
```

**Comment by PandaHugMonster** [comment]
Good morning! I wanna confirm that there is a **Yii::$app null bug** when using **TestCase** or **DbTestCase**.
I was experimenting but couldn't find a workaround.
![2016-09-25 08-52-46](https://cloud.githubusercontent.com/assets/5005505/18813567/6bb915de-82fe-11e6-81dc-828c6c819f2c.png)

**Comment by Ni-san** [comment]
Same issue: Call to a member function has() on null in vendor/codeception/codeception/src/Codeception/Module/Yii2.php:197

Codeception v2.2.5
Yii2 v2.0.9
Yii2-codeception latest (572a6d46d942cc5733c45931fdbd1d60228f3c89)

**Comment by Kolyunya** [comment]
Confirmed.

**Comment by samdark** [comment]
Codeception module was changed so it doesn't work with yii2-codeception anymore. You need to drop it and use module only.

**Comment by Kolyunya** [comment]
@samdark we should update [this](http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html#using-fixtures) then.
