### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by EagleMoor** [yiisoft/yii2-codeception#31]
### Problem

Why i can't use yii2 migration for create test db? It's not problem Codeception, because hi don't have migration. It's problem yii2-codeception, i think.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.10-dev
| PHP version      | 7.1
| Operating system | MacOS Capitan
| Codeception | 2.2.4
| yii2-codeception | dev-master

**Comment by cebe** [comment]
what is the problem? why can't you use migration?

**Comment by EagleMoor** [comment]
How i do it automatically like a Codeception\Module\Db ? I want on start test - up migration, up fixture (if need), do test and down migration.

**Comment by klimov-paul** [comment]
See:
https://github.com/yiisoft/yii2/issues/1772

In particular:
https://github.com/yiisoft/yii2/issues/1772#issuecomment-31605050

**Comment by EagleMoor** [comment]
@klimov-paul i read this. Why it's don't do in this module? If new user start write first test, he don't see in doc, what he need do to create db for test. First idea - it's use migration, but Codeception & Yii don't help with it. Second - save migration to SQL and use Db module, it's not good way, when we use migration.

**Comment by klimov-paul** [comment]
> i read this. 

I doubt it. At yiisoft/yii2#1772 there is a whole disscussion about this there with the explanations why it is not supported out of the box.
The decision is made, there is nothing else I can do. You should apply migrations for your test on your own.

**Comment by EagleMoor** [comment]
Thanks
