### ISSUE TITLE
Should I prefer this extension over direct using Codeception?

### ISSUE THREAD

**Issue by RdeWilde** [yiisoft/yii2-codeception#33]
Or is this outdated/no more maintained?

**Comment by cebe** [comment]
I guess it is outdated as of the refactoring in advanced app that will come with 2.0.10 release. Am I correct, @samdark @DavertMik?

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
We need to deprecate it after 2.0.10 release.
