### ISSUE TITLE
When sending second ajax get request, the codeception selector is not working

### ISSUE THREAD

**Issue by giannisdag** [yiisoft/yii2-codeception#34]
### What steps will reproduce the problem?
I am creating a functional test, where there are two ajax calls on the same page
### What's expected?
After the second request, I should get a form to fill. Specifically, I should get a textarea field, a datetime picker field, and a submit button. I should filled them with submit form or fill field and then click button, and then post them.
### What do you get instead?
I am getting  Element located either by name, CSS or XPath element with '"id":"test1"' was not found

### Additional info
At the steps before the second ajax call, the selector works. I have tested this.
| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | 5.6 fpm
| Operating system | ubuntu 14.04

[MessageCest.txt](https://github.com/yiisoft/yii2-codeception/files/545070/MessageCest.txt)

[backend.tests.MessageCest.tryToSendMessageSuccesfully.fail.txt](https://github.com/yiisoft/yii2-codeception/files/545074/backend.tests.MessageCest.tryToSendMessageSuccesfully.fail.txt)

**Comment by samdark** [comment]
Do you run that via Selenium? If yes, try adding a pause.

**Comment by giannisdag** [comment]
thank you for the quick reply, it is a functional test. I would probably turn this into acceptance, I thought of this possibility, I don' t know if there is something to emulate wait in functional testing.

**Comment by samdark** [comment]
Yes, there is: http://codeception.com/docs/modules/WebDriver#wait

**Comment by giannisdag** [comment]
yes but this is for acceptance testing I think. If I understand you propose to turn this into acceptance test.

**Comment by samdark** [comment]
Ah... nope. If it's not selenium based and page isn't formed via JS it's better to keep it as is.
