### ISSUE TITLE
Undefined index: HTTP_USER_AGENT

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2-codeception#36]
I have just set up codeception. But I'm getting the following error and not sure why or how to fix it.

> LoginFormCest: Login with wrong credentials
>  Test  tests\functional\LoginFormCest.php:loginWithWrongCredentials
> 
>   [yii\base\ErrorException] Undefined index: HTTP_USER_AGENT

When I installed Codeception I did get this message and though a part of this or all of it might be the cause but not sure?

>  symfony/browser-kit suggests installing symfony/process ()
> symfony/event-dispatcher suggests installing symfony/dependency-injection ()
> symfony/event-dispatcher suggests installing symfony/http-kernel ()
> symfony/console suggests installing symfony/process ()
> phpunit/php-code-coverage suggests installing ext-xdebug (>=2.4.0)
> sebastian/global-state suggests installing ext-uopz (*)
> phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
> phpunit/phpunit suggests installing ext-xdebug (*)
> codeception/base suggests installing flow/jsonpath (For using JSONPath in REST m
> odule)
> codeception/base suggests installing phpseclib/phpseclib (for SFTP option in FTP
>  Module)
> codeception/base suggests installing league/factory-muffin (For DataFactory modu
> le)
> codeception/base suggests installing league/factory-muffin-faker (For Faker supp
> ort in DataFactory module)
> codeception/base suggests installing symfony/phpunit-bridge (For phpunit-bridge
> support)

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.10
| PHP version      | 5.6.24
| Operating system | Windows 7

**Comment by samdark** [comment]
These are suggestions and should not cause error.

**Comment by jonny7** [comment]
This doesn't happen in the basic app fresh install. I get this output, the same as what's on the codeception page for Yii:

> $ composer exec codecept run
> Codeception PHP Testing Framework v2.2.5
> Powered by PHPUnit 5.6.1 by Sebastian Bergmann and contributors.
> 
> Functional Tests (10) --------------------------------------
> + ContactFormCest: Open contact page (0.09s)
> + ContactFormCest: Submit empty form (0.03s)
> + ContactFormCest: Submit form with incorrect email (0.02s)
> + ContactFormCest: Submit form successfully (0.06s)
> + LoginFormCest: Open login page (0.01s)
> + LoginFormCest: Internal login by id (0.01s)
> + LoginFormCest: Internal login by instance (0.01s)
> + LoginFormCest: Login with empty credentials (0.01s)
> + LoginFormCest: Login with wrong credentials (0.01s)
> + LoginFormCest: Login successfully (0.01s)
> ------------------------------------------------------------
> 
> Unit Tests (8) ---------------------------------------------
> + ContactFormTest: Email is sent on contact (0.02s)
> + LoginFormTest: Login no user (0.00s)
> + LoginFormTest: Login wrong password (0.00s)
> + LoginFormTest: Login correct (0.00s)
> + UserTest: Find user by id (0.00s)
> + UserTest: Find user by access token (0.00s)
> + UserTest: Find user by username
> + UserTest: Validate user (0.00s)
> ------------------------------------------------------------
> 
> 
> Time: 1.05 seconds, Memory: 28.50MB
> 
> OK (18 tests, 52 assertions)

In my app, where I had to remove a load of packages and reinstall it goes like this and seems to extend past the unit tests.


> Codeception PHP Testing Framework v2.2.5
> Powered by PHPUnit 5.6.2 by Sebastian Bergmann and contributors.
> 
> Functional Tests (6) ---------------------------------------
> E LoginFormCest: Open login page (0.05s)
> E LoginFormCest: Internal login by id (0.00s)
> E LoginFormCest: Internal login by instance (0.00s)
> E LoginFormCest: Login with empty credentials (0.00s)
> E LoginFormCest: Login with wrong credentials (0.00s)
> E LoginFormCest: Login successfully (0.00s)
> ------------------------------------------------------------
> 
> Unit Tests (5) ---------------------------------------------
> E LoginFormTest: Login no user (0.12s)
> E LoginFormTest: Login wrong password (0.10s)
> E LoginFormTest: Login correct (0.10s)
> + UserTest: Find by email (0.95s)
> S UserTest: Validate user (0.00s)
> ------------------------------------------------------------
> 1) LoginFormCest: Open login page
>  Test  tests\functional\LoginFormCest.php:openLoginPage
> 
>   [yii\base\ErrorException] Undefined index: HTTP_USER_AGENT
> 
> 
> Scenario Steps:
> 
>  1. $I->amOnRoute("site/login")
> ...

**Comment by samdark** [comment]
Well, compare with what's in default app and try to find out the reason. Nothing comes into mind which could easily fix it.

**Comment by jonny7** [comment]
I've tried to narrow this down. My `LoginFormCest.php` is:

```
class LoginFormCest
{
    public function _before(\FunctionalTester $I)
    {
        $I->amOnRoute('site/login');
    }

    public function openLoginPage(\FunctionalTester $I)
    {
        $I->see('Login');
    }
}
```

LoginFormTest.php

```
namespace tests\models;

use app\models\LoginForm;
use Codeception\Specify;

class LoginFormTest extends \Codeception\Test\Unit
{
    private $model;

    protected function _after()
    {
        \Yii::$app->user->logout();
    }
}
```

When I run with debug: 

> Functional Tests (1) ---------------------------------------
> Modules: Filesystem, Yii2
> ------------------------------------------------------------
> LoginFormCest: Open login page
> Signature: LoginFormCest:openLoginPage
> Test: tests\functional\LoginFormCest.php:openLoginPage
> Scenario --
>  I am on route "site/login"
>   [Request Headers] []
>   [yii\db\Connection::open] Opening DB Connection
>   ERROR

Later on it goes to say: 

> 1) LoginFormCest: Open login page
>  Test  tests\functional\LoginFormCest.php:openLoginPage
> 
>   [yii\base\ErrorException] Undefined index: HTTP_USER_AGENT

I couldn't find the docs around this or what this error means to try and fix. I've been through and tried to compare the two installations I have and they seem to be the same in set up. Obviously something is wrong, but where should I focus my efforts

**Comment by samdark** [comment]
Something's trying to get `$_SERVER['HTTP_USER_AGENT']`. Probably logs...

**Comment by dynasource** [comment]
the issue seems to be somewhere in your app. Try to search for 'HTTP_USER_AGENT' in your application and if it is called without the check with isset first.

It couldnt be yii because of proper checks like this 
```php
    public function getUserAgent()
    {
        return isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : null;
    }
```

**Comment by jonny7** [comment]
Genius. It was in my main.php, I'd had some problems setting codeception up from 2.0.9 to 2.0.10, but thought i'd configured it incorrectly. Not it was my application breaking it. Thanks :+1:
