### ISSUE TITLE
mockApplication before setUp()

### ISSUE THREAD

**Issue by vaseninm** [yiisoft/yii2-codeception#4]
Hi.
Now we mocking application after parent setUp()
```php
    protected function setUp()
    {
        parent::setUp();
        $this->mockApplication();
        $this->unloadFixtures();
        $this->loadFixtures();
    }
```
But if we want to use Yii::$app in setUp() or _before(), we get null.

**Comment by Ragazzo** [comment]
any use case on why you want to use it there?

**Comment by vaseninm** [comment]
@Ragazzo for example. We have 3 players. Every player make one bet and my test checks result.
In setUp of TestCase i create 3 players and in each test players make different bets. 
But now we have not db component, because Yii::$app is null.

**Comment by Ragazzo** [comment]
can you provide test case code?

**Comment by vaseninm** [comment]
@Ragazzo sorry. I try to run test now and it now works good.
