### ISSUE TITLE
_bootstrap.php  Here you can initialize variables that will be available to your tests

### ISSUE THREAD

**Issue by cmw520** [yiisoft/yii2-codeception#42]
in the file _bootstrap.php
Here you can initialize variables that will be available to your tests
 how to use it ?

**Comment by dynasource** [comment]
is the place to init global variables. More info at http://codeception.com/docs/02-GettingStarted

**Comment by cmw520** [comment]
http://codeception.com/docs/02-GettingStarted.   I  cannot open this web

**Comment by dynasource** [comment]
thats out of the scope of Yii :)

**Comment by cmw520** [comment]
may i  have your contact information?

**Comment by dynasource** [comment]
Thank you for your question.
In order for this issue tracker to be effective, it should only contain bug reports and feature requests.

We advise you to use our community driven resources:
* [The support forum](http://www.yiiframework.com/forum/)
* [The IRC chat room](http://www.yiiframework.com/chat/)
* [The Gitter chat room](https://gitter.im/yiisoft/yii2)
* [The Definitive Guide to Yii](http://www.yiiframework.com/doc-2.0/guide-index.html)

If you are confident that there is a bug in the framework, feel free to provide information on how to reproduce it. This issue will be closed for now.

**Comment by cmw520** [comment]
...... well

**Comment by dynasource** [comment]
please use the resources I have given you.
