### ISSUE TITLE
Problem with code coverage.

### ISSUE THREAD

**Issue by phpvikas** [yiisoft/yii2-codeception#43]
### What steps will reproduce the problem?
Run codecept run --coverage
### What's expected?
Code coverage report.
### What do you get instead?
  [PHPUnit_Framework_Exception]                                                                                                                
### Additional info
[PHPUnit_Framework_Exception]                                                                                                                
  Argument 1 passed to PHPUnit_Framework_TestResult::setCodeCoverage() must be an instance of SebastianBergmann\CodeCoverage\CodeCoverage, in  
  stance of Codeception\Coverage\DummyCodeCoverage given, called in /var/www/html/biglife/vendor/codeception/base/src/Codeception/Coverage/Su  
  iteSubscriber.php on line 78 and defined   
| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.8
| PHP version      | 5.6.23
| Operating system | ubuntu

**Comment by dynasource** [comment]
https://github.com/yiisoft/yii2/issues/13093
