### ISSUE TITLE
Not compatible with Codeception 2.1 ?

### ISSUE THREAD

**Issue by jbcrouigneau** [yiisoft/yii2-codeception#5]
I updated my project through composer, got codeception 2.1.0, then codeception stopped working.
When I execute "codeception build", I get:

PHP Catchable fatal error:  Argument 1 passed to Codeception\Module::__construct() must be an instance of Codeception\Lib\ModuleContainer, array given, called in /home/jbcrouigneau/.composer/vendor/codeception/codeception/src/Codeception/Configuration.php on line 327 and defined in /home/jbcrouigneau/Development/Project/vendor/codeception/codeception/src/Codeception/Module.php on line 52
PHP Stack trace:
PHP   1. {main}() /home/jbcrouigneau/.composer/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() /home/jbcrouigneau/.composer/vendor/codeception/codeception/codecept:27
PHP   3. Symfony\Component\Console\Application->doRun() /home/jbcrouigneau/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/jbcrouigneau/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /home/jbcrouigneau/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   6. Codeception\Command\Build->execute() /home/jbcrouigneau/.composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   7. Codeception\Command\Build->buildActorsForConfig() /home/jbcrouigneau/.composer/vendor/codeception/codeception/src/Codeception/Command/Build.php:46
PHP   8. Codeception\Lib\Generator\Actor->__construct() /home/jbcrouigneau/.composer/vendor/codeception/codeception/src/Codeception/Command/Build.php:67
PHP   9. Codeception\Configuration::modules() /home/jbcrouigneau/Development/Project/vendor/codeception/codeception/src/Codeception/Lib/Generator/Actor.php:44
PHP  10. Codeception\Configuration::createModule() /home/jbcrouigneau/.composer/vendor/codeception/codeception/src/Codeception/Configuration.php:287
PHP  11. Codeception\Module->__construct() /home/jbcrouigneau/.composer/vendor/codeception/codeception/src/Codeception/Configuration.php:327

**Comment by AnatolyRugalev** [comment]
This kind of errors occured when I tried to launch build with codecept 2.0 installed in global composer storage and when I had codecept 2.1 installed in vendor directory of current project

**Comment by jbcrouigneau** [comment]
Yes! Same cause, same effect. My bad.
Many thanks!

**Comment by kpascal** [comment]
Hi guys, help me out here because I am facing this and banging my head with no end in sight
right now I am getting this while running a directory mixed with Cept and Cest acceptance tests on codeception 2.1.5 

Catchable fatal error: Argument 1 passed to Codeception\Module::__construct() must be an instance of Codeception\Lib\ModuleContainer,
 null given, called in C:\CodeCeption\branches\suites_hydraCodeCeption21\tests\_support\CcHelper.php on line 13 and defined in C:\CodeCeption\branches\suites_hydraCodeCeption21\vendor\codeception\codeception\src\Codeception\Module.php on line 52

here is my cchelper.php
```
    public function __construct($config = null)
    {
        parent::__construct($config);
        $this->suiteName = 'cc';
    }
```

what am I doing wrong 

any help is appreciated

thanks!
